name: .NET publish RELEASE

on:
  release:
    types: [published]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Version Format in Tag            
        uses: nowsprinting/check-version-format-action@v4.0.1
        id: version
        with:
          prefix: 'v'
      - name: Tag invalid
        if: steps.version.outputs.is_valid == 'false'
        run: exit 1
      - uses: actions/checkout@v4
      - name: Verify commit exists in origin/main
        if: steps.version.outputs.is_stable == 'true'
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release /property:Version=${{ steps.version.outputs.major_without_prefix }}
      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
      - name: Push Nuget
        run: dotnet nuget push ./CompositionGenerator/bin/Release/MoDMyNitro.SourceGenerators.Composition.${{ steps.version.outputs.major_without_prefix }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
